### ISSUE TITLE
Clean Listing Code

### ISSUE THREAD

**Issue by cassie1119** [Lucy-426/Rentals#25]
The basic scaffold of the listing view has been written, however as noted by all members the code must be cleaned in terms of comments, duplicate methods and also making adjustments in hard-coding now that the view is more structured.

- [x] Add relevant comments to describe the code + delete anything unnecessary
- [x] Later task but can potentially add javadoc
- [x] Delete duplicate methods and only include/edit those that are relevant
- [x] Modify sections of hard-coding for the view to make it more versatile and 'abstract'

**Comment by Lucy-426** [comment]
Listing code has been edited and refactored to use inputs based on the other components of our program (so all hard-coded values have been removed). The code has also been refactored to follow CA guidelines.
