### ISSUE TITLE
Update home page view after filtering

### ISSUE THREAD

**Issue by az1005** [Lucy-426/Rentals#28]
Once the user has chosen their desired filters and/or typed in the search bar, after clicking the search button, the scroll pane on the home window should be updated to match the listings that fit with these filters. The default shows all the listings when no filtering has been done yet.
- [x] Add an instance attribute to the HomeSearchState for the list of listings to display
- [x] Create buttons for listings in the scroll pane
- [x] Update the functionality of the search button to update the state of the view 
- [x] Update the functionality of the search button to repaint the scroll pane/rename buttons with the new listings

**Comment by Lucy-426** [comment]
All tasks completed for this and filtering method has been merged into develop.
